server:
  port: 9091

spring:
  application:
    name: leave-service
  cloud:
    nacos:
      discovery:
        server-addr: vian.nacos.cn
        username: nacos
        password: nacos
        namespace: public
    sentinel:
      transport:
        dashboard: localhost:18080
        client-ip: 172.16.15.245
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-sentinel
            group-id: DEFAULT_GROUP
            rule-type: flow
            username: nacos
            password: nacos
      eager: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.148.223:30346/db_leave?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: root
    password: 1qazxsw2