server:
  port: 9091

spring:
  cloud:
    # 该配置解决启动报 Cannot determine local hostname错误问题
    inetutils:
      ignored-interfaces: 'TAP-Windows Adapter V9'
    nacos:
      discovery:
        server-addr: single.nacos.cn:8848
        username: nacos
        password: 1qazxsw2
#        namespace: DEV
    sentinel:
      transport:
        dashboard: single.sentinel.cn:8858
        client-ip: 172.16.15.245
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-flow-rules
            group-id: leave
            namespace: DEV
            rule-type: flow
            username: ${spring.cloud.nacos.discovery.username}
            password: ${spring.cloud.nacos.discovery.password}
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-degrade-rules
            group-id: leave
            namespace: DEV
            rule-type: degrade
            username: ${spring.cloud.nacos.discovery.username}
            password: ${spring.cloud.nacos.discovery.password}
      eager: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://single.mysql.cn:3306/db_leave?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: root
    password: 1qazxsw2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.16.15.245:9090
  rabbitmq:
    host: single.rabbitmq.cn
    port: 5672
    username: rabbit
    password: qwerh123
    publisher-returns: true
    publisher-confirm-type: correlated
management:
  endpoints:
    web: #将所有可用的监控指标项对外暴露
      exposure: #可以访问 /actuator/sentinel进行查看Sentinel监控项
        include: '*'
setting:
  upload-addr: 10.0.149.211:8272
  path: /text/backup