server:
  port: 9090

spring:
  application:
    name: leave-system
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public