server:
  port: 9090

spring:
  cloud:
    nacos:
      discovery:
        server-addr: single.nacos.cn:8848
        username: nacos
        password: 1qazxsw2
#        namespace: DEV
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.148.133:30346/db_leave?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: root
    password: 1qazxsw2
  security:
    oauth2:
      client:
        registration:
          github-idp:
            provider: github
            client-id: 2205af0f0cc93e3a22ea
            client-secret: 649d88df840a57d2591c4832b438cc9af2727240
            #            redirect-uri: http://192.168.56.1:9000/login/oauth2/code/github-idp # 这个地方可以不配置，配置就要与github的应用配置回调一致
            scope: user:email, read:user
            client-name: Sign in with GitHub
          gitee:
            # 指定oauth登录提供者，该oauth登录由provider中的gitee来处理
            provider: gitee
            # 客户端名字
            client-name: Sign in with Gitee
            # 认证方式
            authorization-grant-type: authorization_code
            # 客户端id，使用自己的gitee的客户端id
            client-id: 29b85c97ed682910eaa4276d84a0c4532f00b962e1b9fe8552520129e65ae432
            # 客户端秘钥，使用自己的gitee的客户端秘钥
            client-secret: 8c6df920482a83d4662a34b76a9c3a62c8e80713e4f2957bb0459c3ceb70d73b
            # 回调地址 与gitee 配置的回调地址一致才行
            redirect-uri: http://172.16.15.245:9090/login/oauth2/code/gitee
            # 申请scope列表
            scope:
              - emails
              - user_info
        provider:
          github:
            user-name-attribute: login
          gitee:
            # 设置用户信息名称对应的字段属性
            user-name-attribute: login
            # 获取token的地址
            token-uri: https://gitee.com/oauth/token
            # 获取用户信息的地址
            user-info-uri: https://gitee.com/api/v5/user
            # 发起授权申请的地址
            authorization-uri: https://gitee.com/oauth/authorize

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org.springframework.security.oauth2.client: trace